# Use tensorflow as base image.
FROM ubuntu:xenial-20190515 
# Install Java and Apache Ignite.
#ADD http://mirror.linux-ia64.org/apache//ignite/2.7.0/apache-ignite-2.7.0-bin.zip apache-ignite-2.7.0-SNAPSHOT-bin.zip
#RUN apt-get update && apt-get install -y openjdk-8-jre unzip && unzip apache-ignite-2.7.0-SNAPSHOT-bin.zip && rm *.zip
ADD apache-ignite-2.7.0-SNAPSHOT-bin apache-ignite-2.7.0-SNAPSHOT-bin
RUN apt-get update && apt-get install -y openjdk-8-jre unzip
# Move ignite-tensorflow from optional into lib folder.
RUN mv apache-ignite-2.7.0-SNAPSHOT-bin/libs/optional/ignite-tensorflow apache-ignite-2.7.0-SNAPSHOT-bin/libs/ignite-tensorflow
# Install model dependencies.
ADD models/official/requirements.txt requirements.txt
RUN apt install -y python3-pip
RUN pip3 install --user -r requirements.txt
# Add Apache Ignite configuration.
ADD ignite-config.xml ignite-config.xml

# modified section #

RUN pip3 install pyignite

# add cifar10 dataset to be loaded into ignite
ADD cifar10_data/cifar-10-batches-bin cifar10_data/cifar-10-batches-bin

# Add script to load cifar10 dataset into ignite cluster
ADD load_cache_kube.py load_cache_docker_network.py

# add script to run cifar10 training
ADD run_cifar10_taining.sh run_cifar10_taining.sh

# Add Resnet model
ADD models models

# add apache kubernetes lib

RUN mv apache-ignite-2.7.0-SNAPSHOT-bin/libs/optional/ignite-rest-http apache-ignite-2.7.0-SNAPSHOT-bin/libs/ignite-rest-http

# end modified section #

# Start Apache Ignite.
CMD bash
