version: '3'

services:
  ignite-server:
    build: .
    networks:
      - net
    expose:
      - "10500"
      - "10800"

networks:
  net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24
